object Versions {
    const val ktx = "1.7.0"
    const val appCompact = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val espressoCore = "3.4.0"
    const val retrofit = "2.9.0"
    const val koin = "3.2.2"
    const val okHttpLogging = "4.9.3"
    const val lifecycle = "2.4.0-alpha03"
    const val mockk = "1.13.4"
    const val coroutines = "1.6.4"
    const val turbine = "0.12.1"
}